// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd0EDqUkTSaA0sfiBJS68V-hPEPRA0f1U',
    appId: '1:820287800448:web:3d1c93fd4e849da292d265',
    messagingSenderId: '820287800448',
    projectId: 'flutterauth-c7076',
    authDomain: 'flutterauth-c7076.firebaseapp.com',
    storageBucket: 'flutterauth-c7076.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFG0DWPV5F87x6xYZOszkiUCTmwvYS1IY',
    appId: '1:820287800448:android:e4d0901972d2201292d265',
    messagingSenderId: '820287800448',
    projectId: 'flutterauth-c7076',
    storageBucket: 'flutterauth-c7076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZFxnlCZkMkMhO8mEVW4fT0B5GoK_hXq0',
    appId: '1:820287800448:ios:fcd232298671801592d265',
    messagingSenderId: '820287800448',
    projectId: 'flutterauth-c7076',
    storageBucket: 'flutterauth-c7076.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZFxnlCZkMkMhO8mEVW4fT0B5GoK_hXq0',
    appId: '1:820287800448:ios:fcd232298671801592d265',
    messagingSenderId: '820287800448',
    projectId: 'flutterauth-c7076',
    storageBucket: 'flutterauth-c7076.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd0EDqUkTSaA0sfiBJS68V-hPEPRA0f1U',
    appId: '1:820287800448:web:e01dce977fa6d56092d265',
    messagingSenderId: '820287800448',
    projectId: 'flutterauth-c7076',
    authDomain: 'flutterauth-c7076.firebaseapp.com',
    storageBucket: 'flutterauth-c7076.firebasestorage.app',
  );
}
